### ISSUE TITLE
手机浏览word

### ISSUE THREAD

**Issue by BaiYuncangGo** [Hypdncy/NessusToReport#16]
发现竟然还藏了一个安恒logo，真的服你

**Comment by Hypdncy** [comment]
什么叫做我隐藏的，这个最开始就是安恒的模板，后来被公司要求删除，才改成现在这样，你不会说话就别在这乱说话

**Comment by BaiYuncangGo** [comment]
抱歉可能语气不太好，因为做好后IOS看的到安恒水印，但是安卓的手机看不到。

**Comment by Hypdncy** [comment]
图片的水印我没找到，确实有几处文字水印，我已经删除了，看看新文件是否存在

**Comment by BaiYuncangGo** [comment]
![4eaea81e3fd106b95b3304a426fcd1e](https://user-images.githubusercontent.com/85089269/146486641-d3481ed8-7a23-4f0a-b836-73f686642c83.jpg)
IOS端预览就会显示这个，我是找不到这个图片放在那里

**Comment by Hypdncy** [comment]
重新做模板就好了

**Comment by Hypdncy** [comment]
已经删除了、在信息里有个水印
