### ISSUE TITLE
报错 大佬求解

### ISSUE THREAD

**Issue by feel3000** [Hypdncy/NessusToReport#19]
2022-01-06 21:51:28,464 - root - INFO - 开始初始化数据
2022-01-06 21:51:28,464 - root - INFO - ---开始读取数据
2022-01-06 21:51:28,478 - root - INFO - ----漏洞种类总数：4
2022-01-06 21:51:28,479 - root - INFO - ----漏洞主机总数：3
2022-01-06 21:51:28,479 - root - INFO - ---开始翻译数据
2022-01-06 21:51:28,483 - root - INFO - ------翻译漏洞总数：1
0, message='Attempt to decode JSON with unexpected mimetype: image/gif', url=URL('http://api.fanyi.baidu.com/api/trans/vip/translate?q=Add+the+attribute+'autocomplete%3Doff'+to+these+fields+to+prevent+browsers+from+caching+credentials.&from=auto&to=zh&salt=54476&sign=bfc8ea7358634cb940b3d53df50xxxx&appid=202201060010xxxxx')
0, message='Attempt to decode JSON with unexpected mimetype: image/gif', url=URL('http://api.fanyi.baidu.com/api/trans/vip/translate?q=Web+Server+Allows+Password+Auto-Completion&from=auto&to=zh&salt=3xxxx3&sign=42ca49b292b3604408a8c2aa2f1xxxxx&appid=20220106001xxxxx‘)
0, message='Attempt to decode JSON with unexpected mimetype: image/gif', url=URL('http://api.fanyi.baidu.com/api/trans/vip/translate?q=The+remote+web+server+contains+at+least+one+HTML+form+field+that+has+an+input+of+type+'password'+where+'autocomplete'+is+not+set+to+'off'.+While+this+does+not+represent+a+risk+to+this+web+server+per+se,+it+does+mean+that+users+who+use+the+affected+forms+may+have+their+credentials+saved+in+their+browsers,+which+could+in+turn+lead+to+a+loss+of+confidentiality+if+any+of+them+use+a+shared+host+or+if+their+machine+is+compromised+at+some+point.&from=auto&to=zh&salt=38xxx&sign=b338b0e604d5c821d06fcd80c74xxxxx&appid=2022010xxxxxxxxx')
Traceback (most recent call last):
  File "C:\Users\feel3\Desktop\NessusToReport-master\main.py", line 45, in <module>
    h = Handle(args.docxtype)
  File "C:\Users\feel3\Desktop\NessusToReport-master\modle\handle.py", line 57, in __init__
    TranBaidu(self.LOOPHOLES).run()
  File "C:\Users\feel3\Desktop\NessusToReport-master\modle\common\translate\base.py", line 105, in run
    for plugin_id, type_cn, resinfo in cn_resinfos:
TypeError: cannot unpack non-iterable NoneType object

**Comment by dulong666** [comment]
我跟你问题一样，我百度好有道的API都填写了都不行

**Comment by Hypdncy** [comment]
nessus导出的csv发下呗

**Comment by dulong666** [comment]
我刚刚测试出来问题了，小的CSV文件不会报错，可以正常导出报告；大的CSV文件会进行如下的报错
![error1](https://user-images.githubusercontent.com/58097248/148725745-5fbd591d-be7e-43e2-817f-f7516a5218ae.jpg)

之前没注意到我的报错跟上面的不一样...
不知道这个问题是不是师傅之前说的API限制问题，如果是的话，那就打扰了。
我这边的CSV也给师傅看看。
链接: 
https://pan.baidu.com/s/1TG_52PCFHQLLM2MrqcKx7w?pwd=i4jm
提取码: i4jm

**Comment by Hypdncy** [comment]
报错一般出现在翻译处，观察翻译漏洞总数，翻译漏洞总数较大的时候，并发高可能出现报错，换个网络环境好的地方就好了，我这里翻译你发的big.csv无问题

**Comment by BambooLove** [comment]
师傅你好，我这边采用的三百兆的带宽跟4G的流量进行了测试，依旧是不行。如果师傅有时间调整的话，给师傅几点建议：
1、调低并发的线程以满足大多数用户的需求，毕竟不是很多人都有很好的网络环境。
2、设置自定义线程/并发的功能，让用户根据自己的情况进行设定，默认线程不应太高。
3、Hypdncy师傅这个工具写很不错，期待能够越来越好。Thanks~

**Comment by Hypdncy** [comment]
const.py中
translate_sem = 9  # 协程限制
translate_qps = 9  # qps限制
自身有一套方案解决QPS限制的，你可以调整下这些值

**Comment by BambooLove** [comment]
我把这两个值都调到了3，程序运行的速度变慢了很多，但是依旧翻译不出来那个大的文件（小于200K的是可以的）...
我用的Python版本是3.10的，不知道跟这个有没有关系...
不知道是不是我长得丑的问题，呜呜呜~

**Comment by Hypdncy** [comment]
有可能是脸黑，哈哈哈，我之前碰到这种情况时用的是某单位的网，然后秒换5G，就完事了。。。。

**Comment by safebaseline** [comment]
同样的问题

**Comment by echoyzt** [comment]
> 我刚刚测试出来问题了，小的CSV文件不会报错，可以正常导出报告；大的CSV文件会进行如下的报错 ![error1](https://user-images.githubusercontent.com/58097248/148725745-5fbd591d-be7e-43e2-817f-f7516a5218ae.jpg)
> 
> 之前没注意到我的报错跟上面的不一样... 不知道这个问题是不是师傅之前说的API限制问题，如果是的话，那就打扰了。 我这边的CSV也给师傅看看。 链接: https://pan.baidu.com/s/1TG_52PCFHQLLM2MrqcKx7w?pwd=i4jm 提取码: i4jm

这个问题怎么解决？我遇到同样的问题。

**Comment by BambooLove** [comment]
@echoyzt

**Comment by BambooLove** [comment]
@echoyzt 按照如下方式解决：
1、网络不要太差
2、QPS不要太大，一般默认就行
3、采用付费的翻译API（重点）
