### ISSUE TITLE
既然要靠更新db来匹配，为什么还要引入翻译啊，我想问一下翻译的是什么，因为我今天导出报告发现漏了好多漏洞，我去db里面自己添加了一条那个漏洞的数据，但是还是没有用不知道啥原因，所以这个翻译真的是摆着看的吗

### ISSUE THREAD

**Issue by j5519726** [Hypdncy/NessusToReport#27]

**Comment by Hypdncy** [comment]
本意是想大家一起维护一个db，保持db的最新，但是现在我放弃了
现在每次的翻译结果都会自动添加到db中，下次就不用翻译了

**Comment by j5519726** [comment]
大哥你终于回我了，我试了试你的新版本，但是啥也翻译不出来，改了百度api也翻译不出来，都是0。你要不要自己试试看

**Comment by j5519726** [comment]
可是报告里面也是空的咋办啊

**Comment by Hypdncy** [comment]
你看下config中是不是配置了nessus_only_ip

**Comment by j5519726** [comment]
是的，删除了nessus_only_ip里面的值以后可以翻译了，但是还是漏了很多漏洞，跟最早的时候一样，我仔细看了下翻译漏洞总数和本地更新漏洞数量是0，感觉没有成功翻译，因为我自己手动对比了csv报告里面的漏洞和输出报告的漏洞，并且去db里面看了，没有相关漏洞记录。然后我又把teanble的api换成百度的加上原先申请的key也是一样的。

**Comment by Hypdncy** [comment]
还有忽略的，默认忽略了一些版本不支持的漏洞

**Comment by j5519726** [comment]
好的感谢大哥
