### ISSUE TITLE
请问缺少文件吗？

### ISSUE THREAD

**Issue by mastersir-lab** [Hypdncy/NessusToReport#28]
<img width="1099" alt="image" src="https://user-images.githubusercontent.com/55268579/211489148-18a100f9-a25b-4c73-bede-633899fe9b31.png">

**Comment by Hypdncy** [comment]
是的已修复

**Comment by mastersir-lab** [comment]
谢谢师傅

**Comment by mastersir-lab** [comment]
师傅，麻烦您看下我这是什么情况，是我电脑的问题吗？
<img width="953" alt="image" src="https://user-images.githubusercontent.com/55268579/211493051-00e0b490-8547-48cb-b84e-562ab61ee4b9.png">

**Comment by Hypdncy** [comment]
执行路径不对，要在nesstoreport目录下执行python main.py

**Comment by mastersir-lab** [comment]
确实，我添加个全局获取路径可以运行了，谢谢师傅
