### ISSUE TITLE
一直报这个错误：400, message='Can not decode content-encoding: brotli (br). Please install `Brotli`'

### ISSUE THREAD

**Issue by phons** [Hypdncy/NessusToReport#29]
2023-01-16 22:36:33,282 - root - INFO - 开始初始化数据
2023-01-16 22:36:33,282 - root - INFO - ---开始读取数据
2023-01-16 22:36:33,336 - root - INFO - ----漏洞种类总数：76
2023-01-16 22:36:33,336 - root - INFO - ----漏洞主机总数：13
2023-01-16 22:36:33,336 - root - INFO - ---开始翻译数据
2023-01-16 22:36:33,338 - root - INFO - ------翻译漏洞总数：25
400, message='Can not decode content-encoding: brotli (br). Please install `Brotli`', url=URL('https://zh-cn.tenable.com/plugins/nessus/130092')
400, message='Can not decode content-encoding: brotli (br). Please install `Brotli`', url=URL('https://zh-cn.tenable.com/plugins/nessus/137654')
400, message='Can not decode content-encoding: brotli (br). Please install `Brotli`', url=URL('https://zh-cn.tenable.com/plugins/nessus/117951')
400, message='Can not decode content-encoding: brotli (br). Please install `Brotli`', url=URL('https://zh-cn.tenable.com/plugins/nessus/131325')
400, message='Can not decode content-encoding: brotli (br). Please install `Brotli`', url=URL('https://zh-cn.tenable.com/plugins/nessus/137835')
400, message='Can not decode content-encoding: brotli (br). Please install `Brotli`', url=URL('https://zh-cn.tenable.com/plugins/nessus/130021')
400, message='Can not decode content-encoding: brotli (br). Please install `Brotli`', url=URL('https://zh-cn.tenable.com/plugins/nessus/137407')
400, message='Can not decode content-encoding: brotli (br). Please install `Brotli`', url=URL('https://zh-cn.tenable.com/plugins/nessus/132048')

Traceback (most recent call last):
TypeError: cannot unpack non-iterable NoneType object

这是咋回事

**Comment by Godson5547** [comment]
pip install brotli

**Comment by Hypdncy** [comment]
pip install beautifulsoup4
