### ISSUE TITLE
可以添加一个汇总主机漏洞数量的表格么？

### ISSUE THREAD

**Issue by timetravel-boy** [Hypdncy/NessusToReport#33]
把每个主机对应的高、中、低漏洞数量进行汇总到一个表格里

**Comment by Hypdncy** [comment]
可以，下周一来取

发自我的 iPhone

在 2023年3月14日，16:55，timetravel-boy ***@***.***> 写道：

﻿

把每个主机对应的高、中、低漏洞数量进行汇总到一个表格里

**Comment by Hypdncy** [comment]
漏洞汇总表格已出，请查收
