### ISSUE TITLE
使用最新版本没有配置别的翻译,提取不出来漏洞,老版本依然可以提取,请问是什么原因

### ISSUE THREAD

**Issue by xmqaq** [Hypdncy/NessusToReport#34]
<img width="868" alt="截屏2023-03-17 15 13 28" src="https://user-images.githubusercontent.com/50257557/225837379-70050bf7-4e59-4090-a50f-6d1d79ab01de.png">

**Comment by Hypdncy** [comment]
可能配置了nessus_only_ips

**Comment by xmqaq** [comment]
感谢,已解决问题
