### ISSUE TITLE
大佬出现这个问题是什么原因  Please install `Brotli`'

### ISSUE THREAD

**Issue by relic-oss** [Hypdncy/NessusToReport#43]
![PixPin_2024-03-22_10-06-18](https://github.com/Hypdncy/NessusToReport/assets/73701126/27bf4456-d89d-4c59-99ea-b40d04713d71)

**Comment by Hypdncy** [comment]
检查下modle/common/translate/tenable.py,这个很久没更新了和官网的可能不一致
一般情况下只需要重百度网盘把vuldb下载然后替换即可

**Comment by relic-oss** [comment]
![PixPin_2024-03-22_10-15-39](https://github.com/Hypdncy/NessusToReport/assets/73701126/0570d14f-98e9-4cb3-a331-5fd4bd22b872)
现在报解析的问题了
