### ISSUE TITLE
大佬，报了一个编码的错误

### ISSUE THREAD

**Issue by relic-oss** [Hypdncy/NessusToReport#44]
![Uploading PixPin_2024-03-22_10-15-39.png…]()

**Comment by Hypdncy** [comment]
hypdncy@163.com发送到这里

**Comment by relic-oss** [comment]
没事了，我解决了，改了一下代码

**Comment by yokaisec** [comment]
> 没事了，我解决了，改了一下代码

怎么解决的 ？？我也遇到这个问题了
