### ISSUE TITLE
添加appid和key运行报keyerror

### ISSUE THREAD

**Issue by GetBlackjake** [Hypdncy/NessusToReport#8]
![image](https://user-images.githubusercontent.com/48322172/119691762-6d5e0600-be7d-11eb-814b-a5cfcf7ce6b3.png)
是什么原因

**Comment by Hypdncy** [comment]
搜索并替换
translate_baidu_appid = "XXXXXX"
translate_baidu_secret = "XXXXXX"
升级为百度高级版用户
